### ISSUE TITLE
魅蓝note不可以用

### ISSUE THREAD

**Issue by poorbug** [gengen1988/cordova-plugin-baidu-geolocation#4]
问题1：
需要添加cordova-plugin-geolocation插件吗？

问题2：
这个是封装了android 定位SDK吗？

问题3：
除了conig.xml添加配置外，还需要什么其他配置吗？

安卓获取不到GPS定位，据说是因为Google被墙？我不会写安卓代码，定位这个问题已经困扰我好几天了。。。

**Comment by gengen1988** [comment]
1. 不需要；
2. 封装了 Baidu 的定位服务，没有使用 Android SDK 的；
3. 需要你在 Baidu 上有个开发者帐号，注册一个自己的地理应用；

这个就是为了防止 Google 被墙而导致的 GPS 无法定位的插件。内部的网络定位用的是百度的服务而不是 Android 设备自带的，因此需要先去百度注册自己的应用。

**Comment by poorbug** [comment]
谢谢回复！

我使用的AK是android端的

目前测试了几个机型，结果如下

定位成功: 
1. 联想K910(4.4.2)
2. 红米(4.2.2)
3. nexus4(5.1.1)

定位失败：
1. 魅蓝note(4.4.4)
2. 华为P8(5.0.2)
3. 华为mate7(4.2.2)

应该是和品牌有关系，和安卓版本无关

**Comment by gengen1988** [comment]
作为临时的解决方案你可以在定位失败的机型里用官方的插件（或者根本不用插件，官方的插件就是一个空实现）。

如果可以用，临时发布两个版本。在这段时间里，从 Android 的日志里寻找为何无法定位的原因。

可以用 `adb logcat` 来查看日志。

**Comment by poorbug** [comment]
这个问题先搁置了，如果我有啥解决方案或者问题再来回复~谢谢了
